apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: base-dependencies
  namespace: flux-system
spec:
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./clusters/base
  prune: false
  timeout: 10m