apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: api-release-gitops
  namespace: flux-system
spec:
  interval: 1m
  targetNamespace: go-test-ns
  chart:
    spec:
      chart: ./charts/phylax
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
