apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "phylax.fullname" . }}
  labels:
    konghq.com/credential: key-auth
type: Opaque
stringData:
  key: {{ include "phylax.fullname" . }}
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name:  {{ include "phylax.fullname" . }}
  annotations:
      kubernetes.io/ingress.class: kong
username:  {{ include "phylax.fullname" . }}
credentials:
- {{ include "phylax.fullname" . }}