apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "phylax.fullname" . }}
spec:
  gatewayClassName: kong-gateway-class
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      routes:
        kind: HTTPRoute
        selector:
          matchLabels:
            gateway: kong
        namespaces:
          from: All
