name: Build and Push to GHCR

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to use'     
        required: true
        default: 'main'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        app:
          - name: go-api-server
            dockerfile: Dockerfile
            context: .
            env: dev

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV


    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image to GHCR
      uses: docker/build-push-action@v2
      with:
        context: ${{ matrix.app.context }}
        file: ${{ matrix.app.dockerfile }}
        push: true
        tags: |
          ghcr.io/saintskeeper/anon-infra-funtimes${{ matrix.app.name }}:${{matrix.app.env}}-${{ env.SHORT_SHA }}